/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojecttfis;

import javax.swing.JOptionPane;

/**
 *
 * @author Scm96Steven
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI1
     */
    Jugador[] jugadores;
    
    
    
    
    public GUI(Jugador[] players) {
        initComponents();
         setSize(1000, 530);
         listaJugadas.setVisible(false);
         BotonJugada1.setSelected(true);
        BotonJugador1.setSelected(true);
      jugadores = players;
      
    }

    String currentPlay;
    String currentPlayer; //nombre del Jugador 2 en el array
     int playerIterator;
    Partida currentGame = new Partida(jugadores,3);
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersButtonGroup = new javax.swing.ButtonGroup();
        playsButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonJugada9 = new javax.swing.JRadioButton();
        BotonJugador1 = new javax.swing.JRadioButton();
        BotonJugada8 = new javax.swing.JRadioButton();
        BotonJugador2 = new javax.swing.JRadioButton();
        BotonJugada7 = new javax.swing.JRadioButton();
        agregarJugada = new javax.swing.JButton();
        BotonJugada6 = new javax.swing.JRadioButton();
        BotonJugada5 = new javax.swing.JRadioButton();
        BotonJugada4 = new javax.swing.JRadioButton();
        BotonJugada3 = new javax.swing.JRadioButton();
        BotonJugada2 = new javax.swing.JRadioButton();
        BotonJugada1 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        adv_2 = new javax.swing.JLabel();
        score_2 = new javax.swing.JLabel();
        set1_2 = new javax.swing.JLabel();
        set2_2 = new javax.swing.JLabel();
        set3_2 = new javax.swing.JLabel();
        set4_2 = new javax.swing.JLabel();
        set5_2 = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        set1_1 = new javax.swing.JLabel();
        set2_1 = new javax.swing.JLabel();
        set3_1 = new javax.swing.JLabel();
        set4_1 = new javax.swing.JLabel();
        set5_1 = new javax.swing.JLabel();
        score_1 = new javax.swing.JLabel();
        adv_1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel3.setText("Jugada:");

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel2.setText("Seleccione jugador:");

        playsButtonGroup.add(BotonJugada9);
        BotonJugada9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada9.setText("Slice");
        BotonJugada9.setOpaque(false);
        BotonJugada9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada9ActionPerformed(evt);
            }
        });

        playersButtonGroup.add(BotonJugador1);
        BotonJugador1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugador1.setText("Jugador 1");
        BotonJugador1.setOpaque(false);
        BotonJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugador1ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada8);
        BotonJugada8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada8.setText("Globo");
        BotonJugada8.setOpaque(false);
        BotonJugada8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada8ActionPerformed(evt);
            }
        });

        playersButtonGroup.add(BotonJugador2);
        BotonJugador2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugador2.setText("Jugador 2");
        BotonJugador2.setOpaque(false);
        BotonJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugador2ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada7);
        BotonJugada7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada7.setText("Remate o Smash");
        BotonJugada7.setOpaque(false);
        BotonJugada7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada7ActionPerformed(evt);
            }
        });

        agregarJugada.setBackground(new java.awt.Color(204, 204, 204));
        agregarJugada.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        agregarJugada.setText("Agregar jugada");
        agregarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarJugadaActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada6);
        BotonJugada6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada6.setText("Contradejada");
        BotonJugada6.setOpaque(false);
        BotonJugada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada6ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada5);
        BotonJugada5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada5.setText("Dejada");
        BotonJugada5.setOpaque(false);
        BotonJugada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada5ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada4);
        BotonJugada4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada4.setText("Reves");
        BotonJugada4.setOpaque(false);
        BotonJugada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada4ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada3);
        BotonJugada3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada3.setText("Volea");
        BotonJugada3.setOpaque(false);
        BotonJugada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada3ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada2);
        BotonJugada2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada2.setText("Derecha o drive");
        BotonJugada2.setOpaque(false);
        BotonJugada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada2ActionPerformed(evt);
            }
        });

        playsButtonGroup.add(BotonJugada1);
        BotonJugada1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada1.setText("Saque");
        BotonJugada1.setOpaque(false);
        BotonJugada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Rockwell Condensed", 1, 15)); // NOI18N
        jLabel22.setText("Status:");

        jLabel27.setFont(new java.awt.Font("Rockwell Condensed", 1, 15)); // NOI18N
        jLabel27.setText("Set:");

        jLabel23.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel23.setText("Tabla de scores:");

        listaJugadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaJugadas);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel1.setText("Historial de Jugadas:");

        adv_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        adv_2.setText("jLabel21");

        score_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        score_2.setText("jLabel18");

        set1_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set1_2.setText("jLabel15");

        set2_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set2_2.setText("jLabel16");

        set3_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set3_2.setText("jLabel17");

        set4_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set4_2.setText("jLabel17");

        set5_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set5_2.setText("jLabel17");

        player2Label.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        player2Label.setText("Jugador 2");

        player1Label.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        player1Label.setText("Jugador 1");

        set1_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set1_1.setText("jLabel11");

        set2_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set2_1.setText("jLabel12");

        set3_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set3_1.setText("jLabel13");

        set4_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set4_1.setText("jLabel13");

        set5_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set5_1.setText("jLabel13");

        score_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        score_1.setText("jLabel14");

        adv_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        adv_1.setText("jLabel20");

        jLabel19.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel19.setText("Adv.");

        jLabel10.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel10.setText("Score");

        jLabel9.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel9.setText("Set 3");

        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel8.setText("Set 2");

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel7.setText("Set 1");

        jLabel11.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel11.setText("Set 4");

        jLabel12.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel12.setText("Set 5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonJugada2)
                            .addComponent(BotonJugada3)
                            .addComponent(BotonJugada9)
                            .addComponent(BotonJugada1)
                            .addComponent(BotonJugada4)
                            .addComponent(agregarJugada)
                            .addComponent(BotonJugada5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotonJugada7)
                                        .addComponent(BotonJugada6)
                                        .addComponent(BotonJugada8))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BotonJugador1)
                                        .addComponent(BotonJugador2)
                                        .addComponent(jLabel3)))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel22))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(adv_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(adv_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(score_2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(score_1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(player2Label)
                                                .addGap(70, 70, 70)
                                                .addComponent(set2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(player1Label)
                                                .addGap(70, 70, 70)
                                                .addComponent(set2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(set3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(set3_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(set1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel7))
                                            .addComponent(set1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel8)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(set4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(set4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(set5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(set5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addGap(77, 77, 77)))
                        .addGap(79, 79, 79)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonJugador1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(BotonJugador2)))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(player1Label)
                                            .addComponent(set1_1)
                                            .addComponent(set3_1)
                                            .addComponent(set2_1))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(player2Label)
                                            .addComponent(set1_2)
                                            .addComponent(set3_2)
                                            .addComponent(set2_2)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, 0)
                                        .addComponent(set4_1)
                                        .addGap(11, 11, 11)
                                        .addComponent(set4_2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, 0)
                                        .addComponent(set5_1)
                                        .addGap(11, 11, 11)
                                        .addComponent(set5_2))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, 0)
                                        .addComponent(adv_1)
                                        .addGap(11, 11, 11)
                                        .addComponent(adv_2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, 0)
                                        .addComponent(score_1)
                                        .addGap(11, 11, 11)
                                        .addComponent(score_2)))
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(BotonJugada5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(BotonJugada2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(BotonJugada3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(BotonJugada6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(BotonJugada9))
                            .addComponent(BotonJugada1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonJugada7)
                                    .addComponent(jLabel27)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonJugada8)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(BotonJugada4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarJugada))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Anotar Jugada", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultar historial anterior", jPanel3);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1042, 706);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonJugada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada1ActionPerformed
        // TODO add your handling code here:
        //Cada vez que se selecciona una jugada se almacena su nombre en currentPlay para imprimirlo al historial. Igual para las demas juagdas debajo.
        currentPlay = "Saque";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada1ActionPerformed

    private void BotonJugada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada2ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Derecha";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada2ActionPerformed

    private void BotonJugada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada3ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Volea";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada3ActionPerformed

    private void BotonJugada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada4ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Reves";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada4ActionPerformed

    private void BotonJugada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada5ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Dejada";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada5ActionPerformed

    private void BotonJugada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada6ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Contra Dejada";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada6ActionPerformed

    private void agregarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarJugadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarJugadaActionPerformed

    private void BotonJugada7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada7ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Remate";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada7ActionPerformed

    private void BotonJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugador2ActionPerformed
        // TODO add your handling code here:
        currentPlayer = jugadores[1].toString(); //nombre del Jugador 2 en el array
        playerIterator = 1; //Posicion del jugador 2 en el array
        System.out.println(currentPlayer);
    }//GEN-LAST:event_BotonJugador2ActionPerformed

    private void BotonJugada8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada8ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Globo";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada8ActionPerformed

    private void BotonJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugador1ActionPerformed
        // TODO add your handling code here:
        currentPlayer = jugadores[0].toString(); //Se extrae el nombre del jugador
        playerIterator = 0; //Posicion del player 1.
        System.out.println(currentPlayer);//Se imprime a consola el player seleccionado
    }//GEN-LAST:event_BotonJugador1ActionPerformed

    private void BotonJugada9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada9ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Slice";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(jugadores).setVisible(true);
            }
        });
    }
    public void addPlay(){
        int oponent = (playerIterator + 1) % 2;
        Boolean deuceWinner = false;
        
        
        if (currentGame.jugadores[playerIterator].score[currentGame.set] == 6 && currentGame.jugadores[oponent].score[currentGame.set] == 6){
            currentGame.status="Tie Break";
            System.out.println("Tie break");
            currentGame.listData[currentGame.listIterator++] = "Tie break";
            currentGame.playerScore[currentGame.scoreIterator]++;
            if (currentGame.playerScore[currentGame.scoreIterator] >= 7) {
                if (Math.abs(currentGame.playerScore[currentGame.scoreIterator] - currentGame.playerScore[oponent]) >= 2) {
                    jugadores[currentGame.scoreIterator].score[currentGame.set]++;
                    currentGame.playerScore[currentGame.scoreIterator] = 0;
                    currentGame.playerScore[oponent] = 0;
                    currentGame.listData[currentGame.listIterator++] = "Gana el tie break el" + jugadores[currentGame.scoreIterator].toString();
                    currentGame.set++;
                    currentGame.playerSets[currentGame.scoreIterator]++;
                    currentGame.status = "Partida Normal";
                }
            }
            
        }else { //Si no hay Tie break, entonces sigue la jugada normal.
            if (currentGame.set <= 3 && currentGame.game) {

                if (currentGame.playerScore[currentGame.scoreIterator] == 0) { //Actualiza el score
                    currentGame.playerScore[currentGame.scoreIterator] = 15;
                } else if (currentGame.playerScore[currentGame.scoreIterator] == 15) {//Actualiza el score
                    currentGame.playerScore[currentGame.scoreIterator] = 30;
                } else if (currentGame.playerScore[currentGame.scoreIterator] == 30) {//Actualiza el score
                    currentGame.playerScore[currentGame.scoreIterator] = 40;//Esta excepcion se utiliza para que cuando un jugador gane un Deuce, se imprima primero la jugada y luego que gano el deuce.
                    currentGame.listData[currentGame.listIterator++] = (currentPlayer + ", " + currentPlay + ", Set:" + Integer.toString(currentGame.set + 1) + ", Score:" + Integer.toString(currentGame.playerScore[currentGame.scoreIterator]));
                    if (currentGame.playerScore[currentGame.scoreIterator] == currentGame.playerScore[oponent]) { //Si ambos tienen 40 y 40 de score, entran en deuce.
                        currentGame.status = "Deuce"; 
                        currentGame.listData[currentGame.listIterator++] = "Deuce"; //Se imprime deuce en la lista
                    }
                } else if (currentGame.playerScore[currentGame.scoreIterator] == 40) {

                    if (currentGame.playerScore[currentGame.scoreIterator] != currentGame.playerScore[oponent]) //No hay deuce
                    {
                        currentGame.playerScore[currentGame.scoreIterator] = 0;
                        jugadores[currentGame.scoreIterator].score[currentGame.set]++; //Se sube el score ya que alcanzo los 40 puntos y 1 mas.
                        System.out.println("Hace un game el " + jugadores[currentGame.scoreIterator].toString());
                        currentGame.listData[currentGame.listIterator++] = "Hace un game el " + jugadores[currentGame.scoreIterator].toString();
                    } else //Si hay deuce entonces...
                    {
                        //Se imprime el score del deuce.
                        currentGame.listData[currentGame.listIterator++] = (currentPlayer + ", " + currentPlay + ", Set:" + Integer.toString(currentGame.set + 1) + ", Score:" + Integer.toString(currentGame.advanceArr[currentGame.scoreIterator] + 1));
                        currentGame.status = "Deuce";
                        currentGame.advanceArr[currentGame.scoreIterator]++; //Se suma score al jugador correspondiente
                        if (Math.abs(currentGame.advanceArr[currentGame.scoreIterator] - currentGame.advanceArr[oponent]) < 2) //Si aun nadie tiene ventaja de dos
                        {

                            if (currentGame.advanceArr[currentGame.scoreIterator] == currentGame.advanceArr[oponent]) //si se empata adv con adv, se resetea el AdvanceArr
                            {
                                currentGame.advanceArr[currentGame.scoreIterator] = 0;
                                currentGame.advanceArr[oponent] = 0;
                                System.out.println("Se empato el deuce");
                                currentGame.listData[currentGame.listIterator++] = "Se empato el deuce";
                            }
                        } else { 
                            currentGame.playerScore[currentGame.scoreIterator] = 0; 
                            currentGame.playerScore[oponent] = 0;

                            jugadores[currentGame.scoreIterator].score[currentGame.set]++;

                        }
                        if (Math.abs(currentGame.advanceArr[currentGame.scoreIterator] - currentGame.advanceArr[oponent]) == 2) { //si alguien tiene ventaja de 2. Gana el deuce
                            System.out.println("score " + jugadores[currentGame.scoreIterator].toString() + jugadores[currentGame.scoreIterator].score[currentGame.set]);
                            deuceWinner = true; 
                            setTableText();
                            currentGame.advanceArr[currentGame.scoreIterator] = 0; //Se resetea el array para un proximo deuce.
                            currentGame.advanceArr[oponent] = 0; //Se resetea el array para un proximo deuce.
                            currentGame.status = "Partida Normal";
                        }

                    }

                }

            }
            if (jugadores[currentGame.scoreIterator].score[currentGame.set] == 7) //Caso en el que esta 6 a 5. Se necesitan 7 puntos para ganar
            {
                System.out.println(" jugador tiene 7 y otro 5");
                currentGame.set++;
                currentGame.playerSets[currentGame.scoreIterator]++;
            } else if (jugadores[currentGame.scoreIterator].score[currentGame.set] == 6 && jugadores[oponent].score[currentGame.set] <= 4) { 
                //Si un player alcanza 6 y el otro tiene 4 o menos games entonces este gana el set
                //gana el set el jugador que hizo la jugada
                System.out.println(" 6 y menor que 4");
                currentGame.set++;
                currentGame.playerSets[currentGame.scoreIterator]++;
            }

            System.out.println(currentGame.playerScore[currentGame.scoreIterator]);
            listaJugadas.setVisible(true); 
            if (currentGame.playerScore[currentGame.scoreIterator] != 0 && currentGame.playerScore[currentGame.scoreIterator] != 40) {
                currentGame.listData[currentGame.listIterator++] = (currentPlayer + ", " + currentPlay + ", Set:" + Integer.toString(currentGame.set + 1) + ", Score:" + Integer.toString(currentGame.playerScore[currentGame.scoreIterator]));
            }
            if (deuceWinner == true) { //Si alguien gano el deuce(en caso de haber ocurrido). Se imprime quien lo gano.
                System.out.println("Gana el deuce el " + jugadores[currentGame.scoreIterator].toString());
                currentGame.listData[currentGame.listIterator++] = "Gana el deuce el " + jugadores[currentGame.scoreIterator].toString();
                deuceWinner = false;
            }

            listaJugadas.setListData(currentGame.listData); //Se actualiza el historial de jugadas con las nuevas jugadas.

            setTableText(); //Se actualizan los labels de la tabla de score.

        }
        if (currentGame.playerSets[currentGame.scoreIterator] >= 2 && currentGame.game) { //Si un jugador tiene mas de 2 sets de 3, este gana la partida.
            System.out.println("Gana el partido el " + jugadores[currentGame.scoreIterator].toString());
            currentGame.listData[currentGame.listIterator++] = "Gana el Partido el " + jugadores[currentGame.scoreIterator].toString();
            currentGame.game = false;
            currentGame.status = ("Ganador : " + jugadores[currentGame.scoreIterator].toString());
            JOptionPane.showMessageDialog(null, "Gana el Partido el " + jugadores[currentGame.scoreIterator].toString()); //Aviso de que un jugador gano la partida.

        }
        statusLabel.setText(currentGame.status); //Se actualiza el status al correspondiente segun lo que haya pasado en la jugada.
        setTableText();
    }
    
     public void setTableText() {
        //Sirve para setear el valor de la tabla de score correspondiente en cada label.

        jLabel11.setText(String.valueOf(jugadores[0].score[0]));
        jLabel12.setText(String.valueOf(jugadores[0].score[1]));
        jLabel13.setText(String.valueOf(jugadores[0].score[2]));
        jLabel14.setText(String.valueOf(currentGame.playerScore[0]));
        jLabel15.setText(String.valueOf(jugadores[1].score[0]));
        jLabel16.setText(String.valueOf(jugadores[1].score[1]));
        jLabel17.setText(String.valueOf(jugadores[1].score[2]));
        jLabel18.setText(String.valueOf(currentGameplayerScore[1]));
        jLabel20.setText("");
        jLabel21.setText("");
        if (advanceArr[0] == 1) { 
            jLabel20.setText("*");
        }
        if (advanceArr[1] == 1) {
            jLabel21.setText("*");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonJugada1;
    private javax.swing.JRadioButton BotonJugada2;
    private javax.swing.JRadioButton BotonJugada3;
    private javax.swing.JRadioButton BotonJugada4;
    private javax.swing.JRadioButton BotonJugada5;
    private javax.swing.JRadioButton BotonJugada6;
    private javax.swing.JRadioButton BotonJugada7;
    private javax.swing.JRadioButton BotonJugada8;
    private javax.swing.JRadioButton BotonJugada9;
    private javax.swing.JRadioButton BotonJugador1;
    private javax.swing.JRadioButton BotonJugador2;
    private javax.swing.JLabel adv_1;
    private javax.swing.JLabel adv_2;
    private javax.swing.JButton agregarJugada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaJugadas;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private javax.swing.ButtonGroup playersButtonGroup;
    private javax.swing.ButtonGroup playsButtonGroup;
    private javax.swing.JLabel score_1;
    private javax.swing.JLabel score_2;
    private javax.swing.JLabel set1_1;
    private javax.swing.JLabel set1_2;
    private javax.swing.JLabel set2_1;
    private javax.swing.JLabel set2_2;
    private javax.swing.JLabel set3_1;
    private javax.swing.JLabel set3_2;
    private javax.swing.JLabel set4_1;
    private javax.swing.JLabel set4_2;
    private javax.swing.JLabel set5_1;
    private javax.swing.JLabel set5_2;
    // End of variables declaration//GEN-END:variables
}
