/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojecttfis;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Scm96Steven
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI1
     */
    Jugador[] jugadores;
     Partida currentGame;
        ManejoTxt mt;
    
    
    public  GUI() {
        initComponents();
         setSize(1000, 530);
         listaJugadas.setVisible(false);
        
         BotonJugada1.setSelected(true);
        BotonJugador1.setSelected(true);
      jugadores = PantallaInicial.jugadores;
     player1Label.setText(jugadores[0].toString());
      player2Label.setText(jugadores[1].toString());
        System.out.println(PantallaInicial.setSize);
       currentGame = new Partida(jugadores,PantallaInicial.setSize);
 mt = new ManejoTxt();  
       currentGame.tabla.setTableText();
         
    }

    String currentPlay="Saque";
    String currentPlayer; //nombre del Jugador 2 en el array
     int playerIterator;
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersButtonGroup = new javax.swing.ButtonGroup();
        playsButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BotonJugada9 = new javax.swing.JRadioButton();
        BotonJugada8 = new javax.swing.JRadioButton();
        BotonJugada7 = new javax.swing.JRadioButton();
        BotonJugada6 = new javax.swing.JRadioButton();
        BotonJugada5 = new javax.swing.JRadioButton();
        BotonJugada4 = new javax.swing.JRadioButton();
        BotonJugada3 = new javax.swing.JRadioButton();
        BotonJugada2 = new javax.swing.JRadioButton();
        BotonJugada1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        BotonJugador1 = new javax.swing.JRadioButton();
        BotonJugador2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        agregarJugada = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        saveHistorialButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        adv_1 = new javax.swing.JLabel();
        adv_2 = new javax.swing.JLabel();
        score_2 = new javax.swing.JLabel();
        score_1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        set1_2 = new javax.swing.JLabel();
        set1_1 = new javax.swing.JLabel();
        set1 = new javax.swing.JLabel();
        set2 = new javax.swing.JLabel();
        set2_1 = new javax.swing.JLabel();
        set2_2 = new javax.swing.JLabel();
        set3_2 = new javax.swing.JLabel();
        set3_1 = new javax.swing.JLabel();
        set3 = new javax.swing.JLabel();
        set4 = new javax.swing.JLabel();
        set4_1 = new javax.swing.JLabel();
        set4_2 = new javax.swing.JLabel();
        set5_2 = new javax.swing.JLabel();
        set5_1 = new javax.swing.JLabel();
        set5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 10, 10);

        playsButtonGroup.add(BotonJugada9);
        BotonJugada9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada9.setText("Slice");
        BotonJugada9.setOpaque(false);
        BotonJugada9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada9ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada9);
        BotonJugada9.setBounds(20, 370, 61, 23);

        playsButtonGroup.add(BotonJugada8);
        BotonJugada8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada8.setText("Globo");
        BotonJugada8.setOpaque(false);
        BotonJugada8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada8ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada8);
        BotonJugada8.setBounds(20, 350, 61, 23);

        playsButtonGroup.add(BotonJugada7);
        BotonJugada7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada7.setText("Remate o Smash");
        BotonJugada7.setOpaque(false);
        BotonJugada7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada7ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada7);
        BotonJugada7.setBounds(20, 330, 123, 23);

        playsButtonGroup.add(BotonJugada6);
        BotonJugada6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada6.setText("Contradejada");
        BotonJugada6.setOpaque(false);
        BotonJugada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada6ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada6);
        BotonJugada6.setBounds(20, 310, 109, 23);

        playsButtonGroup.add(BotonJugada5);
        BotonJugada5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada5.setText("Dejada");
        BotonJugada5.setOpaque(false);
        BotonJugada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada5ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada5);
        BotonJugada5.setBounds(20, 290, 67, 24);

        playsButtonGroup.add(BotonJugada4);
        BotonJugada4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada4.setText("Reves");
        BotonJugada4.setOpaque(false);
        BotonJugada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada4ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada4);
        BotonJugada4.setBounds(20, 270, 61, 23);

        playsButtonGroup.add(BotonJugada3);
        BotonJugada3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada3.setText("Volea");
        BotonJugada3.setOpaque(false);
        BotonJugada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada3);
        BotonJugada3.setBounds(20, 250, 61, 23);

        playsButtonGroup.add(BotonJugada2);
        BotonJugada2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada2.setText("Derecha o drive");
        BotonJugada2.setOpaque(false);
        BotonJugada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada2);
        BotonJugada2.setBounds(20, 230, 131, 23);

        playsButtonGroup.add(BotonJugada1);
        BotonJugada1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugada1.setText("Saque");
        BotonJugada1.setOpaque(false);
        BotonJugada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugada1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugada1);
        BotonJugada1.setBounds(20, 210, 61, 23);

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel3.setText("Jugada:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 50, 20);

        playersButtonGroup.add(BotonJugador1);
        BotonJugador1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugador1.setText("Jugador 1");
        BotonJugador1.setOpaque(false);
        BotonJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugador1);
        BotonJugador1.setBounds(20, 130, 89, 23);

        playersButtonGroup.add(BotonJugador2);
        BotonJugador2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        BotonJugador2.setText("Jugador 2");
        BotonJugador2.setOpaque(false);
        BotonJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonJugador2);
        BotonJugador2.setBounds(20, 150, 89, 23);

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel2.setText("Seleccione jugador:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 160, 20);

        agregarJugada.setBackground(new java.awt.Color(204, 204, 204));
        agregarJugada.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        agregarJugada.setText("Agregar jugada");
        agregarJugada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarJugadaActionPerformed(evt);
            }
        });
        getContentPane().add(agregarJugada);
        agregarJugada.setBounds(30, 410, 121, 27);

        jLabel22.setFont(new java.awt.Font("Rockwell Condensed", 1, 15)); // NOI18N
        jLabel22.setText("Status:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(250, 370, 41, 19);

        jLabel27.setFont(new java.awt.Font("Rockwell Condensed", 1, 15)); // NOI18N
        jLabel27.setText("Set:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(250, 340, 22, 19);

        statusLabel.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        statusLabel.setText("jLabel18");
        getContentPane().add(statusLabel);
        statusLabel.setBounds(300, 370, 90, 19);

        saveHistorialButton.setBackground(new java.awt.Color(204, 204, 204));
        saveHistorialButton.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        saveHistorialButton.setText("Guardar Historial");
        saveHistorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHistorialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveHistorialButton);
        saveHistorialButton.setBounds(700, 420, 140, 27);

        jLabel19.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel19.setText("Adv.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(260, 240, 29, 20);

        adv_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        adv_1.setText("jLabel20");
        getContentPane().add(adv_1);
        adv_1.setBounds(270, 260, 27, 19);

        adv_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        adv_2.setText("jLabel21");
        getContentPane().add(adv_2);
        adv_2.setBounds(270, 290, 27, 19);

        score_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        score_2.setText("jLabel18");
        getContentPane().add(score_2);
        score_2.setBounds(320, 290, 21, 19);

        score_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        score_1.setText("jLabel14");
        getContentPane().add(score_1);
        score_1.setBounds(320, 260, 29, 19);

        jLabel10.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel10.setText("Score");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 240, 35, 20);

        player1Label.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        player1Label.setText("Jugador 1");
        getContentPane().add(player1Label);
        player1Label.setBounds(350, 260, 110, 15);

        player2Label.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        player2Label.setText("Jugador 2");
        getContentPane().add(player2Label);
        player2Label.setBounds(350, 290, 120, 15);

        set1_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set1_2.setText("jLabel15");
        getContentPane().add(set1_2);
        set1_2.setBounds(460, 290, 25, 19);

        set1_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set1_1.setText("jLabel11");
        getContentPane().add(set1_1);
        set1_1.setBounds(460, 260, 25, 19);

        set1.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        set1.setText("Set 1");
        getContentPane().add(set1);
        set1.setBounds(460, 240, 31, 20);

        set2.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        set2.setText("Set 2");
        getContentPane().add(set2);
        set2.setBounds(510, 240, 31, 20);

        set2_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set2_1.setText("jLabel12");
        getContentPane().add(set2_1);
        set2_1.setBounds(510, 260, 25, 19);

        set2_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set2_2.setText("jLabel16");
        getContentPane().add(set2_2);
        set2_2.setBounds(510, 290, 25, 19);

        set3_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set3_2.setText("jLabel17");
        getContentPane().add(set3_2);
        set3_2.setBounds(560, 290, 25, 19);

        set3_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set3_1.setText("jLabel13");
        getContentPane().add(set3_1);
        set3_1.setBounds(560, 260, 25, 19);

        set3.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        set3.setText("Set 3");
        getContentPane().add(set3);
        set3.setBounds(560, 240, 31, 20);

        set4.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        set4.setText("Set 4");
        getContentPane().add(set4);
        set4.setBounds(610, 240, 31, 20);

        set4_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set4_1.setText("jLabel13");
        getContentPane().add(set4_1);
        set4_1.setBounds(610, 260, 25, 19);

        set4_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set4_2.setText("jLabel17");
        getContentPane().add(set4_2);
        set4_2.setBounds(610, 290, 25, 19);

        set5_2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set5_2.setText("jLabel17");
        getContentPane().add(set5_2);
        set5_2.setBounds(650, 290, 25, 19);

        set5_1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        set5_1.setText("jLabel13");
        getContentPane().add(set5_1);
        set5_1.setBounds(650, 260, 25, 19);

        set5.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        set5.setText("Set 5");
        getContentPane().add(set5);
        set5.setBounds(650, 240, 31, 20);

        jLabel23.setFont(new java.awt.Font("Rockwell Condensed", 1, 16)); // NOI18N
        jLabel23.setText("Tabla de scores:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(380, 190, 108, 20);

        listaJugadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaJugadas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(700, 120, 250, 290);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel1.setText("Historial de Jugadas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(700, 100, 120, 18);

        exitButton.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(880, 420, 59, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarJugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarJugadaActionPerformed
        // TODO add your handling code here:
        currentGame.addPlay(playerIterator, currentPlay);
        currentGame.tabla.setTableText();
    }//GEN-LAST:event_agregarJugadaActionPerformed

    private void BotonJugada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada1ActionPerformed
        // TODO add your handling code here:
        //Cada vez que se selecciona una jugada se almacena su nombre en currentPlay para imprimirlo al historial. Igual para las demas juagdas debajo.
        currentPlay = "Saque";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada1ActionPerformed

    private void BotonJugada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada2ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Derecha";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada2ActionPerformed

    private void BotonJugada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada3ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Volea";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada3ActionPerformed

    private void BotonJugada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada4ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Reves";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada4ActionPerformed

    private void BotonJugada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada5ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Dejada";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada5ActionPerformed

    private void BotonJugada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada6ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Contra Dejada";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada6ActionPerformed

    private void saveHistorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHistorialButtonActionPerformed
        // TODO add your handling code here:

        try{

            mt.arrayToText(Partida.listData);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveHistorialButtonActionPerformed

    private void BotonJugada7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada7ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Remate";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada7ActionPerformed

    private void BotonJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugador2ActionPerformed
        // TODO add your handling code here:
        currentPlayer = jugadores[1].toString(); //nombre del Jugador 2 en el array
        playerIterator = 1; //Posicion del jugador 2 en el array
        System.out.println(currentPlayer);
    }//GEN-LAST:event_BotonJugador2ActionPerformed

    private void BotonJugada8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada8ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Globo";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada8ActionPerformed

    private void BotonJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugador1ActionPerformed
        // TODO add your handling code here:
        currentPlayer = jugadores[0].toString(); //Se extrae el nombre del jugador
        playerIterator = 0; //Posicion del player 1.
        System.out.println(currentPlayer);//Se imprime a consola el player seleccionado
    }//GEN-LAST:event_BotonJugador1ActionPerformed

    private void BotonJugada9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJugada9ActionPerformed
        // TODO add your handling code here:
        currentPlay = "Slice";
        System.out.println(currentPlay);
    }//GEN-LAST:event_BotonJugada9ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


 
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
   
    }
   

     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonJugada1;
    private javax.swing.JRadioButton BotonJugada2;
    private javax.swing.JRadioButton BotonJugada3;
    private javax.swing.JRadioButton BotonJugada4;
    private javax.swing.JRadioButton BotonJugada5;
    private javax.swing.JRadioButton BotonJugada6;
    private javax.swing.JRadioButton BotonJugada7;
    private javax.swing.JRadioButton BotonJugada8;
    private javax.swing.JRadioButton BotonJugada9;
    private javax.swing.JRadioButton BotonJugador1;
    private javax.swing.JRadioButton BotonJugador2;
    public static javax.swing.JLabel adv_1;
    public static javax.swing.JLabel adv_2;
    public static javax.swing.JButton agregarJugada;
    private javax.swing.JButton exitButton;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> listaJugadas;
    public static javax.swing.JLabel player1Label;
    public static javax.swing.JLabel player2Label;
    private javax.swing.ButtonGroup playersButtonGroup;
    private javax.swing.ButtonGroup playsButtonGroup;
    public static javax.swing.JButton saveHistorialButton;
    public static javax.swing.JLabel score_1;
    public static javax.swing.JLabel score_2;
    public static javax.swing.JLabel set1;
    public static javax.swing.JLabel set1_1;
    public static javax.swing.JLabel set1_2;
    public static javax.swing.JLabel set2;
    public static javax.swing.JLabel set2_1;
    public static javax.swing.JLabel set2_2;
    public static javax.swing.JLabel set3;
    public static javax.swing.JLabel set3_1;
    public static javax.swing.JLabel set3_2;
    public static javax.swing.JLabel set4;
    public static javax.swing.JLabel set4_1;
    public static javax.swing.JLabel set4_2;
    public static javax.swing.JLabel set5;
    public static javax.swing.JLabel set5_1;
    public static javax.swing.JLabel set5_2;
    public static javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
